// Code generated by "stringer -type=Class"; DO NOT EDIT.

package classes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Shield-1]
	_ = x[Glaive-2]
	_ = x[Knife-3]
	_ = x[Bow-4]
}

const _Class_name = "ShieldGlaiveKnifeBow"

var _Class_index = [...]uint8{0, 6, 12, 17, 20}

func (i Class) String() string {
	i -= 1
	if i >= Class(len(_Class_index)-1) {
		return "Class(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
