// Code generated by "stringer -type=Team"; DO NOT EDIT.

package teams

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Blue-1]
	_ = x[Red-2]
}

const _Team_name = "BlueRed"

var _Team_index = [...]uint8{0, 4, 7}

func (i Team) String() string {
	i -= 1
	if i >= Team(len(_Team_index)-1) {
		return "Team(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Team_name[_Team_index[i]:_Team_index[i+1]]
}
