// Code generated by "stringer -type=TurnState"; DO NOT EDIT.

package turnstate

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Input-1]
	_ = x[Action-2]
}

const _TurnState_name = "InputAction"

var _TurnState_index = [...]uint8{0, 5, 11}

func (i TurnState) String() string {
	i -= 1
	if i >= TurnState(len(_TurnState_index)-1) {
		return "TurnState(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _TurnState_name[_TurnState_index[i]:_TurnState_index[i+1]]
}
